import { TheFooter } from '@/components/TheFooter'
import { TheHeader } from '@/components/TheHeader'
import { TheNav } from '@/components/TheNav'
import { Inter } from 'next/font/google'
import '../style/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<TheHeader />
			<TheNav />
			<main className={inter.className}>{children}</main>
			<TheFooter />
		</html>
	)
}
